services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sister-sorting-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env   # this file defines DATABASE_URL, PORT, etc.
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
